server: "hub-cloud.browserstack.com"
user: "<BROWSERSTACK_USERNAME>"
key: "<BROWSERSTACK_ACCESS_KEY>"

common_caps:
  "build": "rspec-appium-browserstack"
  "browserstack.debug": true
  "browserstack.local": true

appium_caps:
  -
    "name": "local_test"
    "device": "Google Pixel"
    "realMobile": true
    "app": "bs://<app_hashed_id>"
